---
site_name: "environmental-sample-schema"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://sierra-moxon.github.io/water-sample-schema
repo_url: https://github.com/sierra-moxon/water-sample-schema

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
